### ISSUE TITLE
Implement User logging to console

### ISSUE THREAD

**Issue by WassimItani** [WassimItani/test#1]
Implement a feature that logs the user's name in the browser's console. Follow the tasks below to complete the feature:

### Tasks:

- [x] Create a new file named `script.js` in the project.
- [x] Append script.js to HTML
- [x] Add a `<p>` element to inform the user about the logging of their name in the console.

**Comment by WassimItani** [comment]
im facing an issue
